pdmtools/pdmtools/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sparevolumecalculator/', include("sparevolumecalculator.urls"))
]

pdmtools/sparevolumecalculator/urls.py
from django.urls import path

from . import views

app_name = "sparevolumecalculator"
urlpatterns = [
    path("", views.index, name="index"),
    path("results", views.results, name="results"),
    path("documentation", views.documentation, name="documentation")
]

pdmtools/sparevolumecalculator/models.py
from django.db import models

# Create your models here.

pdmtools/sparevolumecalculator/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.files.storage import FileSystemStorage
from . import helpers
from . import helpers2

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader

# Create your views here.
def index(request):
    if request.method == "POST":
        width = request.POST.get('width')
    
        return render(request, 'sparevolumecalculator/results.html')
    return render(request, 'sparevolumecalculator/index.html')

def results(request):
    if request.method == "POST":
        width = int(request.POST.get("width"))
        height = int(request.POST.get("height"))
        numCables = int(request.POST.get("numCables"))
        placed_cables = []
        cables = []

        for i in range(numCables):
            cable = int(request.POST.get("cable"+str(i)))
            cables.extend([cable]*int(request.POST.get("number"+str(i))))

        cables = [d/2 for d in cables]
        cables = sorted(cables, reverse=True)

        '''
        CODE FOR VERSION 1 (uncomment if necessary)
        ----------------------------------------------------------------------------------
        for cable in cables:
        helpers.add_cable(height, width, cable, placed_cables)

        helpers.plot_circles_on_grid(placed_cables, height, width)
        spare_volume = helpers.calculate_spare_volume2(height, width, placed_cables)
        ----------------------------------------------------------------------------------
        '''
        helpers2.main_algorithm(cables, height, width)
        # Create a new PDF document
        pdf = canvas.Canvas('sparevolumecalculator/static/results.pdf', pagesize=letter)

        # Set font and size
        pdf.setFont("Helvetica-Bold", 40)

        # Draw the title on the PDF document
        pdf.drawString(250, 750, "Results")

        # Define the text and image to include in the PDF
        image_path = 'sparevolumecalculator/static/images/result.png'

        # Set the position and size of the image
        img = ImageReader(image_path)
        img_width, img_height = img.getSize()
        aspect_ratio = img_height / float(img_width)
        width = 8 * inch
        height = width * aspect_ratio

        # Calculate the position of the image
        y = 650 - height
        x = 0.5 * (letter[0] - width)

        # Draw the text on the PDF document

        # Draw the image on the PDF document
        pdf.drawImage(img, x, y, width=width, height=height)

        # Save the PDF document
        pdf.save()

        return render(request, "sparevolumecalculator/results.html", {'image_file':'/static/images/result.png'})# , 'spare_volume':spare_volume})

def documentation(request):
    return render(request, "sparevolumecalculator/documentation.html", {
        "image_file":"/static/images/documentation.jpg"
        })

pdmtools/sparevolumecalculator/templates/sparevolumecalculator/documentation.html
{% extends "sparevolumecalculator/layout.html" %}

{% block title %}
    Documentation
{% endblock %}

{% block main %}e
    <img src="{{ image_file }}">
{% endblock %}

pdmtools/sparevolumecalculator/templates/sparevolumecalculator/index.html
{% extends "sparevolumecalculator/layout.html" %}

{% block main %}
<script type="text/javascript">
function createInputs() {
  var numInputs = document.getElementById("numInputs").value;
  var inputsDiv = document.getElementById("inputsDiv");
  inputsDiv.innerHTML = "";

  for (var i = 0; i < numInputs; i++) {
    var input1 = document.createElement("input");
    input1.type = "text";
    input1.name = "cable" + i;
    input1.placeholder = "cable " + (i+1);
    inputsDiv.appendChild(input1);

    var input2 = document.createElement("input");
    input2.type = "number";
    input2.name = "number" + i;
    input2.placeholder = "number " + (i+1);
    inputsDiv.appendChild(input2);

    inputsDiv.appendChild(document.createElement("br"));
  }
}
  </script>
  <form action="{% url 'sparevolumecalculator:results' %}", method="post">
    {% csrf_token %}
    <input autocomplete="off" autofocus name="width" placeholder="Gutter width" max="500" type="number">
    <input autocomplete="off" autofocus name="height" placeholder="Gutter height" max="500" type="number">
    <label for="numInputs">Number of cables/bundles:</label>
    <input type="number" id="numInputs" name="numCables" min="1" value="1" onchange="createInputs()">
    <br><br>
    <div id="inputsDiv">

      <br>
    </div>
    <br>
    <input type="submit" value="Submit">
  </form>

{% endblock %}

pdmtools/sparevolumecalculator/templates/sparevolumecalculator/layout.html
<!DOCTYPE html>

<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="initial-scale=1, width=device-width">

        <!-- http://getbootstrap.com/docs/5.1/ -->
        <link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">
        <script crossorigin="anonymous" src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"></script>

        <!-- https://favicon.io/emoji-favicons/money-bag/ -->
        <link href="/static/favicon.ico" rel="icon">

        <link href="/static/styles.css" rel="stylesheet">

        <title>Spare volume calculation tool</title>

    </head>

    <body style="background-color: aliceblue;">

        <nav class="bg-light border navbar navbar-expand-md navbar-light">
            <div class="container-fluid">
                <span class="red">Spare volume calculation tool :) </span></a>
                <button aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-bs-target="#navbar" data-bs-toggle="collapse" type="button">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>

        <main class="container-fluid py-5 text-center">
            {% block main %}{% endblock %}
        </main>
        <div id="page-container">
            <div id="content-wrap">
              <!-- all other page content -->
            </div>
            <footer id="footer" class="mb-5 small text-center text-muted">Don't forget to read the <a href="{% url 'sparevolumecalculator:documentation' %}">documentation</a></footer>
          </div>
    </body>

</html>

pdmtools/sparevolumecalculator/templates/sparevolumecalculator/results.html
{% extends "sparevolumecalculator/layout.html" %}

{% block title %}
    RESULT PAGE
{% endblock %}

{% block main %}
    <h1>Results</h1>
    <h3>The spare volume equals: {{  spare_volume  }}%</h3>
    <img src="{{ image_file }}" alt="My Figure">
    <a href="/static/results.pdf" download>Download PDF</a>
{% endblock %}